

const userData = {
  signinnotInDb: {
    email: 'never@gmail.com',
    password: '1234567677',
  },
  signinInDbBadPWord: {
    email: 'successgilli@gmail.com',
    password: '1234567677',
  },
  signinValid: {
    email: 'successgilli@gmail.com',
    password: 'bearsman',
  },
  user: {
    email: 'successgilli@gmail.com',
    firstName: 'gilbert',
    lastName: 'lastName',
    address: 'road A rivers state',
    password: 'bearsman',
    companyAddress: 'Andela epic towers',
    companyName: 'Andela',
    bvn: '12345678926',
    bankName: 'fidelity',
    accountNumber: '2918392829',
    monthlyIncome: '2000',
    isAdmin: false,
    status: 'unverified',
  },
  baduserFirstName: {
    email: 'successgilli@gmail.com',
    firstName: 'gilbert hhd',
    lastName: 'lastName',
    address: 'road A rivers state',
    password: 'bearsman',
    companyAddress: 'Andela epic towers',
    companyName: 'Andela',
    bvn: '12345678926',
    bankName: 'fidelity',
    accountNumber: '2918392829',
    monthlyIncome: '2000',
    isAdmin: false,
    status: 'unverified',
  },
  baduserLastName: {
    email: 'successgilli@gmail.com',
    firstName: 'gilbert',
    lastName: 'lastName dd',
    address: 'road A rivers state',
    password: 'bearsman',
    companyAddress: 'Andela epic towers',
    companyName: 'Andela',
    bvn: '12345678926',
    bankName: 'fidelity',
    accountNumber: '2918392829',
    monthlyIncome: '2000',
    isAdmin: false,
    status: 'unverified',
  },
  baduserAddress: {
    email: 'successgilli@gmail.com',
    firstName: 'gilbert',
    lastName: 'lastName',
    address: '33333',
    password: 'bearsman',
    companyAddress: 'Andela epic towers',
    companyName: 'Andela',
    bvn: '12345678926',
    bankName: 'fidelity',
    accountNumber: '2918392829',
    monthlyIncome: '2000',
    isAdmin: false,
    status: 'unverified',
  },
  baduserEmail: {
    email: 'successgilli@%gmail.com',
    firstName: 'gilbert',
    lastName: 'lastName',
    address: 'road A rivers state',
    password: 'bearsman',
    companyAddress: 'Andela epic towers',
    companyName: 'Andela',
    bvn: '12345678926',
    bankName: 'fidelity',
    accountNumber: '2918392829',
    monthlyIncome: '2000',
    isAdmin: false,
    status: 'unverified',
  },
  baduserbvn: {
    email: 'successgilli@gmail.com',
    firstName: 'gilbert',
    lastName: 'lastName',
    address: 'road A rivers state',
    password: 'bearsman',
    companyAddress: 'Andela epic towers',
    companyName: 'Andela',
    bvn: '1234567892644',
    bankName: 'fidelity',
    accountNumber: '2918392829',
    monthlyIncome: '2000',
    isAdmin: false,
    status: 'unverified',
  },
  baduserBankName: {
    email: 'successgilli@gmail.com',
    firstName: 'gilbert',
    lastName: 'lastName',
    address: 'road A rivers state',
    password: 'bearsman',
    companyAddress: 'Andela epic towers',
    companyName: 'Andela',
    bvn: '12345678926',
    bankName: 'fidelity y',
    accountNumber: '2918392829',
    monthlyIncome: '2000',
    isAdmin: false,
    status: 'unverified',
  },
  usercompanyAddress: {
    email: 'successgilli@gmail.com',
    firstName: 'gilbert',
    lastName: 'lastName',
    address: 'road A rivers state',
    password: 'bearsman',
    companyAddress: '2222222222',
    companyName: 'Andela',
    bvn: '12345678926',
    bankName: 'fidelityy',
    accountNumber: '2918392829',
    monthlyIncome: '2000',
    isAdmin: false,
    status: 'unverified',
  },
  badUserAcctNo: {
    email: 'successgilli@gmail.com',
    firstName: 'gilbert',
    lastName: 'lastName',
    address: 'road A rivers state',
    password: 'bearsman',
    companyAddress: 'Andela epic towers',
    companyName: 'Andela',
    bvn: '12345678926',
    bankName: 'fidelity',
    accountNumber: '2918392829333',
    monthlyIncome: '2000',
    isAdmin: false,
    status: 'unverified',
  },
  badUsermonthlyIncome: {
    email: 'successgilli@gmail.com',
    firstName: 'gilbert',
    lastName: 'lastName',
    address: 'road A rivers state',
    password: 'bearsman',
    companyAddress: 'Andela epic towers',
    companyName: 'Andela',
    bvn: '12345678926',
    bankName: 'fidelity',
    accountNumber: '2918392829',
    monthlyIncome: '20',
    isAdmin: false,
    status: 'unverified',
  },
  loanAppNoUser: {
    email:'notfound@gmail.com',
    amount: '30000',
    tenor: '8',
  },
  loanAppGood: {
    email:'successgilli@gmail.com',
    amount: '30000',
    tenor: '8',
  },
};

export default userData;